//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iscirzioniWebinar {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl titoloWebinar;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl descrizioneWebinar;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.Literal titolo;
		
		protected System.Web.UI.WebControls.TextBox txtNome;
		
		protected System.Web.UI.WebControls.TextBox txtCognome;
		
		protected System.Web.UI.WebControls.TextBox txtMail;
		
		protected System.Web.UI.WebControls.TextBox txtCF;
		
		protected System.Web.UI.WebControls.TextBox txtTelefono;
		
		protected System.Web.UI.WebControls.TextBox txtRagioneSociale;
		
		protected System.Web.UI.WebControls.TextBox txtPIVA;
		
		protected System.Web.UI.WebControls.RadioButton radioSi;
		
		protected System.Web.UI.WebControls.RadioButton radioNo;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl siCrediti;
		
		protected System.Web.UI.WebControls.DropDownList inputOrdine;
		
		protected System.Web.UI.WebControls.TextBox txtNumeroOrdine;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl noCrediti;
		
		protected System.Web.UI.WebControls.DropDownList inputProvincia;
		
		protected System.Web.UI.HtmlControls.HtmlInputCheckBox checkPrivacy;
		
		protected System.Web.UI.WebControls.Button btnSubmit;
	}
}
